version: '2'
services:

  companies:
    image: registry.jincor.com/backend/companies:latest
    build:
      context: ./
      dockerfile: companies.docker
    ports:
      - 9000
    links:
      - search
      - auth
      - mongo
      - redis
    environment:
      # IMPORTANT: Set the Remote Interpreter entry matching name to `laravel`
      - PHP_IDE_CONFIG="serverName=companies"
    volumes_from:
      - src

  workspace:
    image: registry.jincor.com/backend/companies-workspace:latest-test
    build:
      context: ./
      args:
        - TZ=UTC
        - INSTALL_XDEBUG=true
      dockerfile: workspace.docker
    tty: true
    links:
      - auth
      - mongo
      - redis
      - search
    volumes_from:
      - src


  auth:
    image: registry.jincor.com/backend/auth:latest
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_KEY: "7z3B4gLdSx#fTlAmNnfrYC-;Gp#7fXfOk@cehjUHTWhDjSdcp1"
    volumes:
      - /usr/src/app
    links:
      - redis


  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.2
    environment:
      - cluster.name=jincor-companies
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    ports:
      - 9200

  nginx:
    image: registry.jincor.com/backend/nginx:latest
    volumes_from:
      - src
    ports:
     - 8080:80
     - 443:443
    links:
      - companies


  redis:
    image: registry.jincor.com/backend/redis:latest
    volumes:
          - ./storage/redis:/data

  mongo:
    image: registry.jincor.com/backend/mongodb:latest
    volumes:
          - ./storage/mongodb:/data/db

  src:
    image: tianon/true
    volumes:
      - ./:/var/www/companies
