version: '2'
services:

  companies:
    image: registry.jincor.com/backend/companies
    build:
      context: ./
      dockerfile: companies.docker
    ports:
      - 9000
    links:
      - auth
      - mongo
      - redis
    environment:
      # IMPORTANT: Set the Remote Interpreter entry matching name to `laravel`
      - PHP_IDE_CONFIG="serverName=companies"
    volumes:
      - ./:/var/www/companies

  workspace:
    image: registry.jincor.com/backend/companies-workspace:latest-test
    build:
      context: ./
      args:
        - TZ=UTC
        - INSTALL_XDEBUG=true
      dockerfile: workspace.docker
    tty: true
    links:
      - mongo
      - redis
      - auth
    volumes:
      - ./:/var/www/companies

# The only one reason why auth is here is an API tests in EmployeeChangePasswordCest
# Some cases are trying to interact with real auth server.
# TODO: remove coupling to auth and this service from test docker-compose
  auth:
    image: registry.jincor.com/backend/auth:latest
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_KEY: "7z3B4gLdSx#fTlAmNnfrYC-;Gp#7fXfOk@cehjUHTWhDjSdcp1"
    volumes:
      - /usr/src/app
    links:
      - redis

  redis:
    image: registry.jincor.com/backend/redis:latest
    volumes:
          - ./storage/redis:/data

  mongo:
    image: registry.jincor.com/backend/mongodb:latest
    volumes:
          - ./storage/mongodb:/data/db
