version: '2'
services:

  companies:
    image: registry.jincor.com/backend/companies:latest
    build:
      context: ./
      dockerfile: companies.docker
    ports:
      - 9000
    links:
      - search
      - auth
      - verify
      - mongo
      - redis
    environment:
      # IMPORTANT: Set the Remote Interpreter entry matching name to `laravel`
      - PHP_IDE_CONFIG="serverName=companies"
    volumes_from:
      - src
    networks:
      default:
        ipv4_address: 10.5.0.2

  workspace:
    image: registry.jincor.com/backend/companies-workspace:latest-test
    build:
      context: ./
      args:
        - TZ=UTC
        - INSTALL_XDEBUG=false
      dockerfile: workspace.debug
    tty: true
    links:
      - auth
      - verify
      - mongo
      - redis
      - search
    volumes_from:
      - src
    networks:
      default:
        ipv4_address: 10.5.0.3

  auth:
    image: registry.jincor.com/backend/auth:latest
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      THROTTLER_WHITE_LIST: 127.0.0.1,10.5.0.2,10.5.0.3
      TENANT_WHITE_LIST: 127.0.0.1,10.5.0.2,10.5.0.3
      FORCE_HTTPS: disabled
      JWT_KEY: "7z3B4gLdSx#fTlAmNnfrYC-;Gp#7fXfOk@cehjUHTWhDjSdcp1"
    volumes:
      - /usr/src/app
    links:
      - redis
    networks:
      default:
        ipv4_address: 10.5.0.4

  verify:
    image: registry.jincor.com/backend/verify:latest
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MAIL_DRIVER: ${MAIL_DRIVER}
    links:
      - auth
    networks:
      default:
        ipv4_address: 10.5.0.10

  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.2
    environment:
      - cluster.name=jincor-companies
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    ports:
      - 9200
    networks:
      default:
        ipv4_address: 10.5.0.5

  nginx:
    image: registry.jincor.com/backend/nginx:latest
    volumes_from:
      - src
    ports:
     - 8080:80
     - 443:443
    links:
      - companies
    networks:
      default:
        ipv4_address: 10.5.0.6

  redis:
    image: registry.jincor.com/backend/redis:latest
    volumes:
          - ./storage/redis:/data
    networks:
      default:
        ipv4_address: 10.5.0.7

  mongo:
    image: registry.jincor.com/backend/mongodb:latest
    volumes:
          - ./storage/mongodb:/data/db
    ports:
      - 27017:27017
      - 28017:28017
    networks:
          default:
            ipv4_address: 10.5.0.8

    src:
      image: tianon/true
      volumes:
        - ./:/var/www/companies
    networks:
      default:
        ipv4_address: 10.5.0.9

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
