version: '2'
services:


  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.2
    environment:
      - cluster.name=jincor-companies
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200

  companies:
    build:
      context: ./
      dockerfile: companies.docker
    ports:
      - "9000:9000"
    volumes:
      - "./:/var/www/laravel"
    links:
      - search
#      - auth
      - mongo
      - redis
    extra_hosts:
      # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
      - "dockerhost:10.0.75.1"
    environment:
      # IMPORTANT: Set the Remote Interpreter entry matching name to `laravel`
      - PHP_IDE_CONFIG="serverName=company"

  workspace:
    build:
      context: ./
      args:
        - TZ=UTC
        - INSTALL_XDEBUG=true
      dockerfile: Workspace-Dockerfile
    extra_hosts:
      # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
      - "dockerhost:10.0.75.1"
    ports:
      - "3001:22"
    tty: true
    links:
      - auth
      - mongo
      - nginx
      - redis
      - search
    volumes:
      - "./companies:/var/www/laravel"

  company-worker:
    build:
      context: ./companies
      dockerfile: Queue-Dockerfile
    volumes:
      - "./companies:/var/www/laravel"
    links:
      - redis
      - mongo
      - search
      - auth
    environment:
      - QUEUE=default     # Defaults to 'default'
      - CONNECTION=redis       # Defaults to 'default'


  nginx:
    build:
      context: ./companies
      dockerfile: Nginx-Dockerfile
      args:
        - PHP_UPSTREAM=company
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - "./companies:/var/www/laravel"
    links:
      - company

  redis:
    build:
      context: ./companies
      dockerfile: Redis-Dockerfile
    ports:
      - "6379:6379"

  mongo:
    build:
      context: ./companies
      dockerfile: Mongo-Dockerfile
    ports:
      - "27017:27017"


  frontend_server:
    build:
      context: ./frontend/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
