version: '2'
services:

  workspace:
    image: jincort/backend-company
    build:
      context: ./
      dockerfile: workspace.debug
    tty: true
    links:
      - mongo
      - redis
      - auth
    depends_on:
      - auth
      - redis
      - mongo
    volumes:
      - ./:/var/www/companies
    networks:
          default:
            ipv4_address: 10.5.0.2

# The only one reason why auth is here is an API tests in EmployeeChangePasswordCest
# Some cases are trying to interact with real auth server.
# TODO: remove coupling to auth and this service from test docker-compose
  auth:
    image: jincort/backend-auth:production
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_KEY: "7z3B4gLdSx#fTlAmNnfrYC-;Gp#7fXfOk@cehjUHTWhDjSdcp1"
      TENANT_WHITE_LIST: "10.5.0.2"
    volumes:
      - /usr/src/app
    links:
      - redis
    networks:
          default:
            ipv4_address: 10.5.0.3

  redis:
    image: jincort/backend-redis:production
    volumes:
          - ./storage/redis:/data
    networks:
          default:
            ipv4_address: 10.5.0.4

  mongo:
    image: jincort/backend-mongodb:production
    volumes:
          - ./storage/mongodb:/data/db
    networks:
          default:
            ipv4_address: 10.5.0.5


networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
