<?php

namespace App\Core\DoctrineHydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadataInfo;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class AppCoreValueObjectsCountryISOCodesHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="string") */
        if (isset($data['ISO2Code']) || (! empty($this->class->fieldMappings['ISO2Code']['nullable']) && array_key_exists('ISO2Code', $data))) {
            $value = $data['ISO2Code'];
            if ($value !== null) {
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['ISO2Code']->setValue($document, $return);
            $hydratedData['ISO2Code'] = $return;
        }

        /** @Field(type="integer") */
        if (isset($data['numericCode']) || (! empty($this->class->fieldMappings['numericCode']['nullable']) && array_key_exists('numericCode', $data))) {
            $value = $data['numericCode'];
            if ($value !== null) {
                $return = (int) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['numericCode']->setValue($document, $return);
            $hydratedData['numericCode'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['alpha2Code']) || (! empty($this->class->fieldMappings['alpha2Code']['nullable']) && array_key_exists('alpha2Code', $data))) {
            $value = $data['alpha2Code'];
            if ($value !== null) {
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['alpha2Code']->setValue($document, $return);
            $hydratedData['alpha2Code'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['alpha3Code']) || (! empty($this->class->fieldMappings['alpha3Code']['nullable']) && array_key_exists('alpha3Code', $data))) {
            $value = $data['alpha3Code'];
            if ($value !== null) {
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['alpha3Code']->setValue($document, $return);
            $hydratedData['alpha3Code'] = $return;
        }
        return $hydratedData;
    }
}