<?php

namespace App\Core\DoctrineHydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadataInfo;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class AppCoreDictionaryEntitiesCountryHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="bin_uuid") */
        if (isset($data['_id']) || (! empty($this->class->fieldMappings['id']['nullable']) && array_key_exists('_id', $data))) {
            $value = $data['_id'];
            if ($value !== null) {
                $return = $value !== null ? ($value instanceof \MongoBinData ? $value->bin : $value) : null;
            } else {
                $return = null;
            }
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @EmbedOne */
        if (isset($data['names'])) {
            $embeddedDocument = $data['names'];
            $className = $this->unitOfWork->getClassNameForAssociation($this->class->fieldMappings['names'], $embeddedDocument);
            $embeddedMetadata = $this->dm->getClassMetadata($className);
            $return = $embeddedMetadata->newInstance();

            $this->unitOfWork->setParentAssociation($return, $this->class->fieldMappings['names'], $document, 'names');

            $embeddedData = $this->dm->getHydratorFactory()->hydrate($return, $embeddedDocument, $hints);
            $embeddedId = $embeddedMetadata->identifier && isset($embeddedData[$embeddedMetadata->identifier]) ? $embeddedData[$embeddedMetadata->identifier] : null;

            if (empty($hints[Query::HINT_READ_ONLY])) {
                $this->unitOfWork->registerManaged($return, $embeddedId, $embeddedData);
            }

            $this->class->reflFields['names']->setValue($document, $return);
            $hydratedData['names'] = $return;
        }

        /** @ReferenceOne */
        if (isset($data['currency'])) {
            $reference = $data['currency'];
            if (isset($this->class->fieldMappings['currency']['storeAs']) && $this->class->fieldMappings['currency']['storeAs'] === ClassMetadataInfo::REFERENCE_STORE_AS_ID) {
                $className = $this->class->fieldMappings['currency']['targetDocument'];
                $mongoId = $reference;
            } else {
                $className = $this->unitOfWork->getClassNameForAssociation($this->class->fieldMappings['currency'], $reference);
                $mongoId = $reference['$id'];
            }
            $targetMetadata = $this->dm->getClassMetadata($className);
            $id = $targetMetadata->getPHPIdentifierValue($mongoId);
            $return = $this->dm->getReference($className, $id);
            $this->class->reflFields['currency']->setValue($document, $return);
            $hydratedData['currency'] = $return;
        }

        /** @Field(type="hash") */
        if (isset($data['bounds']) || (! empty($this->class->fieldMappings['bounds']['nullable']) && array_key_exists('bounds', $data))) {
            $value = $data['bounds'];
            if ($value !== null) {
                $return = $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['bounds']->setValue($document, $return);
            $hydratedData['bounds'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['phoneCode']) || (! empty($this->class->fieldMappings['phoneCode']['nullable']) && array_key_exists('phoneCode', $data))) {
            $value = $data['phoneCode'];
            if ($value !== null) {
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['phoneCode']->setValue($document, $return);
            $hydratedData['phoneCode'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['flagUrl']) || (! empty($this->class->fieldMappings['flagUrl']['nullable']) && array_key_exists('flagUrl', $data))) {
            $value = $data['flagUrl'];
            if ($value !== null) {
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['flagUrl']->setValue($document, $return);
            $hydratedData['flagUrl'] = $return;
        }

        /** @EmbedOne */
        if (isset($data['ISOCodes'])) {
            $embeddedDocument = $data['ISOCodes'];
            $className = $this->unitOfWork->getClassNameForAssociation($this->class->fieldMappings['ISOCodes'], $embeddedDocument);
            $embeddedMetadata = $this->dm->getClassMetadata($className);
            $return = $embeddedMetadata->newInstance();

            $this->unitOfWork->setParentAssociation($return, $this->class->fieldMappings['ISOCodes'], $document, 'ISOCodes');

            $embeddedData = $this->dm->getHydratorFactory()->hydrate($return, $embeddedDocument, $hints);
            $embeddedId = $embeddedMetadata->identifier && isset($embeddedData[$embeddedMetadata->identifier]) ? $embeddedData[$embeddedMetadata->identifier] : null;

            if (empty($hints[Query::HINT_READ_ONLY])) {
                $this->unitOfWork->registerManaged($return, $embeddedId, $embeddedData);
            }

            $this->class->reflFields['ISOCodes']->setValue($document, $return);
            $hydratedData['ISOCodes'] = $return;
        }
        return $hydratedData;
    }
}