<?php

namespace App\Core\DoctrineHydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadataInfo;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class AppDomainsCompanyValueObjectsEmployeeProfileHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="string") */
        if (isset($data['position']) || (! empty($this->class->fieldMappings['position']['nullable']) && array_key_exists('position', $data))) {
            $value = $data['position'];
            if ($value !== null) {
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['position']->setValue($document, $return);
            $hydratedData['position'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['firstName']) || (! empty($this->class->fieldMappings['firstName']['nullable']) && array_key_exists('firstName', $data))) {
            $value = $data['firstName'];
            if ($value !== null) {
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['firstName']->setValue($document, $return);
            $hydratedData['firstName'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['lastName']) || (! empty($this->class->fieldMappings['lastName']['nullable']) && array_key_exists('lastName', $data))) {
            $value = $data['lastName'];
            if ($value !== null) {
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['lastName']->setValue($document, $return);
            $hydratedData['lastName'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['login']) || (! empty($this->class->fieldMappings['login']['nullable']) && array_key_exists('login', $data))) {
            $value = $data['login'];
            if ($value !== null) {
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['login']->setValue($document, $return);
            $hydratedData['login'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['extensionNumber']) || (! empty($this->class->fieldMappings['extensionNumber']['nullable']) && array_key_exists('extensionNumber', $data))) {
            $value = $data['extensionNumber'];
            if ($value !== null) {
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['extensionNumber']->setValue($document, $return);
            $hydratedData['extensionNumber'] = $return;
        }
        return $hydratedData;
    }
}