<?php

namespace App\Core\DoctrineProxies\__CG__\App\Core\Dictionary\Entities;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Country extends \App\Core\Dictionary\Entities\Country implements \Doctrine\ODM\MongoDB\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'names', 'currency', 'bounds', 'phoneCode', 'flagUrl', 'ISOCodes'];
        }

        return ['__isInitialized__', 'id', 'names', 'currency', 'bounds', 'phoneCode', 'flagUrl', 'ISOCodes'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Country $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getName($locale = NULL): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', [$locale]);

        return parent::getName($locale);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrency(): \App\Core\Dictionary\Entities\Currency
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrency', []);

        return parent::getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    public function getBounds(): \GeoJson\Geometry\MultiPolygon
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBounds', []);

        return parent::getBounds();
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoneCode(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoneCode', []);

        return parent::getPhoneCode();
    }

    /**
     * {@inheritDoc}
     */
    public function getFlagUrl(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFlagUrl', []);

        return parent::getFlagUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function getNumericCode(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumericCode', []);

        return parent::getNumericCode();
    }

    /**
     * {@inheritDoc}
     */
    public function getAlpha2Code(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlpha2Code', []);

        return parent::getAlpha2Code();
    }

    /**
     * {@inheritDoc}
     */
    public function getAlpha3Code(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlpha3Code', []);

        return parent::getAlpha3Code();
    }

    /**
     * {@inheritDoc}
     */
    public function getISO2Code(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getISO2Code', []);

        return parent::getISO2Code();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNames(array $names)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNames', [$names]);

        return parent::setNames($names);
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrency(\App\Core\Dictionary\Entities\Currency $currency)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrency', [$currency]);

        return parent::setCurrency($currency);
    }

    /**
     * {@inheritDoc}
     */
    public function setBounds(\GeoJson\Geometry\MultiPolygon $bounds)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBounds', [$bounds]);

        return parent::setBounds($bounds);
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoneCode(string $code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoneCode', [$code]);

        return parent::setPhoneCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function setFlagUrl(string $flagUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFlagUrl', [$flagUrl]);

        return parent::setFlagUrl($flagUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function setISOCodes(\App\Core\ValueObjects\CountryISOCodes $ISOCodes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setISOCodes', [$ISOCodes]);

        return parent::setISOCodes($ISOCodes);
    }

}
